### ISSUE TITLE
Not enough  potatoes

### ISSUE THREAD

**Issue by RatInChat** [retronbv/potato-currency#6]
I grind and grind but can never get enough potatoes. Please help with some tips.

**Comment by RedGuy12** [comment]
You can't be talking alone for one thing. The more people there are in a convo, the more dropped potatoes. Also longer messages mean more potatoes.

**Comment by retronbv** [comment]
Are you even in a server with the bot... unless you are self hosting

**Comment by RatInChat** [comment]
it was a joke sorry

**Comment by RatInChat** [comment]
forgive me retron
